

name: Build and Publish


on: 
  push:
    tags:
      - "v*.*.*"

jobs:
  build-and-publish:
    runs-on: ubuntu-18.04
    steps:
      - name: Prepare - Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Prepare - Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Prepare - Get Docker Meta
        id: meta
        uses: docker/metadata-action@v3
        with: 
          images: cc12703/repoupdatenotifyer
          tags: type=ref,event=tags

      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ steps.meta.outputs.tags }}


    